-- [s1]
CREATE SEQUENCE USER_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s2]
CREATE SEQUENCE CATEGORY_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s3]
CREATE SEQUENCE PRODUCT_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s4]
CREATE SEQUENCE CART_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s5]
CREATE SEQUENCE ORDER_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s6]
CREATE SEQUENCE O_DETAIL_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s7]
CREATE SEQUENCE REVIEW_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s8]
CREATE SEQUENCE PAYMENT_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;

-- [s9]
CREATE SEQUENCE SHIPPING_SEQ START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCYCLE;
