-- [t1]
CREATE OR REPLACE TRIGGER USER_TRG
  BEFORE INSERT ON USER_T
  FOR EACH ROW
BEGIN
  IF :NEW.USER_NUM IS NULL THEN
    :NEW.USER_NUM := USER_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t2]
CREATE OR REPLACE TRIGGER CATEGORY_TRG
  BEFORE INSERT ON CATEGORY_T
  FOR EACH ROW
BEGIN
  IF :NEW.CATEGORY_ID IS NULL THEN
    :NEW.CATEGORY_ID := CATEGORY_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t3]
CREATE OR REPLACE TRIGGER PRODUCT_TRG
  BEFORE INSERT ON PRODUCT_T
  FOR EACH ROW
BEGIN
  IF :NEW.PRODUCT_ID IS NULL THEN
    :NEW.PRODUCT_ID := PRODUCT_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t4]
CREATE OR REPLACE TRIGGER CART_TRG
  BEFORE INSERT ON CART_T
  FOR EACH ROW
BEGIN
  IF :NEW.CART_ID IS NULL THEN
    :NEW.CART_ID := CART_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t5]
CREATE OR REPLACE TRIGGER ORDER_TRG
  BEFORE INSERT ON ORDER_T
  FOR EACH ROW
BEGIN
  IF :NEW.ORDER_ID IS NULL THEN
    :NEW.ORDER_ID := ORDER_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t6]
CREATE OR REPLACE TRIGGER O_DETAIL_TRG
  BEFORE INSERT ON O_DETAIL_T
  FOR EACH ROW
BEGIN
  IF :NEW.ORDER_DETAIL_ID IS NULL THEN
    :NEW.ORDER_DETAIL_ID := O_DETAIL_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t7]
CREATE OR REPLACE TRIGGER REVIEW_TRG
  BEFORE INSERT ON REVIEW_T
  FOR EACH ROW
BEGIN
  IF :NEW.REVIEW_ID IS NULL THEN
    :NEW.REVIEW_ID := REVIEW_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t8]
CREATE OR REPLACE TRIGGER PAYMENT_TRG
  BEFORE INSERT ON PAYMENT_T
  FOR EACH ROW
BEGIN
  IF :NEW.PAYMENT_ID IS NULL THEN
    :NEW.PAYMENT_ID := PAYMENT_SEQ.NEXTVAL;
  END IF;
END;
/

-- [t9]
CREATE OR REPLACE TRIGGER SHIPPING_TRG
  BEFORE INSERT ON SHIPPING_T
  FOR EACH ROW
BEGIN
  IF :NEW.SHIPPING_ID IS NULL THEN
    :NEW.SHIPPING_ID := SHIPPING_SEQ.NEXTVAL;
  END IF;
END;
/
